# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import game_pb2 as game__pb2


class SBGameServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_game = channel.unary_unary(
                '/sbgame.SBGameServicer/create_game',
                request_serializer=game__pb2.SBGameState.SerializeToString,
                response_deserializer=game__pb2.SBGameState.FromString,
                )
        self.attempt_guess = channel.unary_unary(
                '/sbgame.SBGameServicer/attempt_guess',
                request_serializer=game__pb2.Attempt.SerializeToString,
                response_deserializer=game__pb2.AttemptEvaluation.FromString,
                )
        self.get_SBGameState = channel.unary_unary(
                '/sbgame.SBGameServicer/get_SBGameState',
                request_serializer=game__pb2.SBGameState.SerializeToString,
                response_deserializer=game__pb2.SBGameState.FromString,
                )
        self.get_highscores = channel.unary_stream(
                '/sbgame.SBGameServicer/get_highscores',
                request_serializer=game__pb2.Player.SerializeToString,
                response_deserializer=game__pb2.SBGameState.FromString,
                )


class SBGameServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_game(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def attempt_guess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_SBGameState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_highscores(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SBGameServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_game': grpc.unary_unary_rpc_method_handler(
                    servicer.create_game,
                    request_deserializer=game__pb2.SBGameState.FromString,
                    response_serializer=game__pb2.SBGameState.SerializeToString,
            ),
            'attempt_guess': grpc.unary_unary_rpc_method_handler(
                    servicer.attempt_guess,
                    request_deserializer=game__pb2.Attempt.FromString,
                    response_serializer=game__pb2.AttemptEvaluation.SerializeToString,
            ),
            'get_SBGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.get_SBGameState,
                    request_deserializer=game__pb2.SBGameState.FromString,
                    response_serializer=game__pb2.SBGameState.SerializeToString,
            ),
            'get_highscores': grpc.unary_stream_rpc_method_handler(
                    servicer.get_highscores,
                    request_deserializer=game__pb2.Player.FromString,
                    response_serializer=game__pb2.SBGameState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sbgame.SBGameServicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SBGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_game(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbgame.SBGameServicer/create_game',
            game__pb2.SBGameState.SerializeToString,
            game__pb2.SBGameState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def attempt_guess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbgame.SBGameServicer/attempt_guess',
            game__pb2.Attempt.SerializeToString,
            game__pb2.AttemptEvaluation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_SBGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sbgame.SBGameServicer/get_SBGameState',
            game__pb2.SBGameState.SerializeToString,
            game__pb2.SBGameState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_highscores(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/sbgame.SBGameServicer/get_highscores',
            game__pb2.Player.SerializeToString,
            game__pb2.SBGameState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
