# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='game.proto',
  package='sbgame',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ngame.proto\x12\x06sbgame\"3\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07session\x18\x03 \x01(\x05\";\n\x07\x41ttempt\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\x0f\n\x07session\x18\x02 \x01(\x05\x12\x11\n\ttimestamp\x18\x03 \x01(\x05\"f\n\x11\x41ttemptEvaluation\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x0e\n\x06points\x18\x03 \x01(\x05\x12\x11\n\ttimestamp\x18\x04 \x01(\x05\x12\x11\n\tattemptId\x18\x05 \x01(\x05\"q\n\x0bSBGameState\x12\x0e\n\x06player\x18\x01 \x01(\t\x12\x0f\n\x07session\x18\x02 \x01(\x05\x12\r\n\x05score\x18\x03 \x01(\x05\x12\r\n\x05tries\x18\x04 \x01(\x05\x12\x10\n\x08wordlist\x18\x05 \x03(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x05\x32\xaa\x02\n\x0eSBGameServicer\x12\x31\n\ncreateGame\x12\x0e.sbgame.Player\x1a\x13.sbgame.SBGameState\x12:\n\x0c\x61ttemptGuess\x12\x0f.sbgame.Attempt\x1a\x19.sbgame.AttemptEvaluation\x12\x35\n\x0egetSBGameState\x12\x0e.sbgame.Player\x1a\x13.sbgame.SBGameState\x12\x37\n\x0egetHighscrores\x12\x0e.sbgame.Player\x1a\x13.sbgame.SBGameState0\x01\x12\x39\n\x10getMyHighscrores\x12\x0e.sbgame.Player\x1a\x13.sbgame.SBGameState0\x01\x62\x06proto3'
)




_PLAYER = _descriptor.Descriptor(
  name='Player',
  full_name='sbgame.Player',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sbgame.Player.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='sbgame.Player.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session', full_name='sbgame.Player.session', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=73,
)


_ATTEMPT = _descriptor.Descriptor(
  name='Attempt',
  full_name='sbgame.Attempt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='sbgame.Attempt.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session', full_name='sbgame.Attempt.session', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sbgame.Attempt.timestamp', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=134,
)


_ATTEMPTEVALUATION = _descriptor.Descriptor(
  name='AttemptEvaluation',
  full_name='sbgame.AttemptEvaluation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid', full_name='sbgame.AttemptEvaluation.valid', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='word', full_name='sbgame.AttemptEvaluation.word', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='points', full_name='sbgame.AttemptEvaluation.points', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sbgame.AttemptEvaluation.timestamp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='attemptId', full_name='sbgame.AttemptEvaluation.attemptId', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=238,
)


_SBGAMESTATE = _descriptor.Descriptor(
  name='SBGameState',
  full_name='sbgame.SBGameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='sbgame.SBGameState.player', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='session', full_name='sbgame.SBGameState.session', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='sbgame.SBGameState.score', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tries', full_name='sbgame.SBGameState.tries', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wordlist', full_name='sbgame.SBGameState.wordlist', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='sbgame.SBGameState.timestamp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=353,
)

DESCRIPTOR.message_types_by_name['Player'] = _PLAYER
DESCRIPTOR.message_types_by_name['Attempt'] = _ATTEMPT
DESCRIPTOR.message_types_by_name['AttemptEvaluation'] = _ATTEMPTEVALUATION
DESCRIPTOR.message_types_by_name['SBGameState'] = _SBGAMESTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Player = _reflection.GeneratedProtocolMessageType('Player', (_message.Message,), {
  'DESCRIPTOR' : _PLAYER,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:sbgame.Player)
  })
_sym_db.RegisterMessage(Player)

Attempt = _reflection.GeneratedProtocolMessageType('Attempt', (_message.Message,), {
  'DESCRIPTOR' : _ATTEMPT,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:sbgame.Attempt)
  })
_sym_db.RegisterMessage(Attempt)

AttemptEvaluation = _reflection.GeneratedProtocolMessageType('AttemptEvaluation', (_message.Message,), {
  'DESCRIPTOR' : _ATTEMPTEVALUATION,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:sbgame.AttemptEvaluation)
  })
_sym_db.RegisterMessage(AttemptEvaluation)

SBGameState = _reflection.GeneratedProtocolMessageType('SBGameState', (_message.Message,), {
  'DESCRIPTOR' : _SBGAMESTATE,
  '__module__' : 'game_pb2'
  # @@protoc_insertion_point(class_scope:sbgame.SBGameState)
  })
_sym_db.RegisterMessage(SBGameState)



_SBGAMESERVICER = _descriptor.ServiceDescriptor(
  name='SBGameServicer',
  full_name='sbgame.SBGameServicer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=356,
  serialized_end=654,
  methods=[
  _descriptor.MethodDescriptor(
    name='createGame',
    full_name='sbgame.SBGameServicer.createGame',
    index=0,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_SBGAMESTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='attemptGuess',
    full_name='sbgame.SBGameServicer.attemptGuess',
    index=1,
    containing_service=None,
    input_type=_ATTEMPT,
    output_type=_ATTEMPTEVALUATION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getSBGameState',
    full_name='sbgame.SBGameServicer.getSBGameState',
    index=2,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_SBGAMESTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getHighscrores',
    full_name='sbgame.SBGameServicer.getHighscrores',
    index=3,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_SBGAMESTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getMyHighscrores',
    full_name='sbgame.SBGameServicer.getMyHighscrores',
    index=4,
    containing_service=None,
    input_type=_PLAYER,
    output_type=_SBGAMESTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SBGAMESERVICER)

DESCRIPTOR.services_by_name['SBGameServicer'] = _SBGAMESERVICER

# @@protoc_insertion_point(module_scope)
